require:


AllCops:
  TargetRubyVersion: 3.3.0
  DisabledByDefault: false
  SuggestExtensions: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 25

Naming/MethodParameterName:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 16

Style/Alias:
  EnforcedStyle: prefer_alias

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TernaryParentheses:
  Enabled: false
  